export const SITE = {
  name: "iRipple",
  primaryCta: "Schedule a Demo",
  salesCta: "Talk to Sales",
};

export const NAV = {
  main: [
    {
      label: "Home",
      path: "/",
    },
    {
      label: "Products",
      path: "/products",
    },
    {
      label: "About",
      path: "/about",
    },
    {
      label: "Careers",
      path: "/careers",
    },
  ],
  products: [
    {
      label: "Barter POS",
      path: "/products/barter-pos",
      id: "barter-pos",
    },
    {
      label: "Barter RMS",
      path: "/products/barter-rms",
      id: "barter-rms",
    },
    {
      label: "Retina Business Intelligence",
      path: "/products/retina-bi",
      id: "retina-bi",
    },
    {
      label: "MyRewards Loyalty",
      path: "/products/myrewards-loyalty",
      id: "myrewards-loyalty",
    },
    {
      label: "Atlas Inventory App",
      path: "/products/atlas-inventory-app",
      id: "atlas-inventory-app",
    },
  ],
  about: [
    {
      label: "History",
      path: "/about/history",
      id: "history",
    },
    {
      label: "Core Values",
      path: "/about/core-values",
      id: "core-values",
    },
    {
      label: "Mission and Vision",
      path: "/about/mission-vision",
      id: "mission-vision",
    },
  ],
};

export const PAGES = {
  home: {
    id: "home",
    label: "Home",
    path: "/",
    title: "Home",
    description:
      "Retail is a daily grind—lines, stockouts, firefighting, late reports. iRipple helps retailers run smoother days: faster checkout, clearer inventory, better d…",
    sections: [
      {
        order: 1.0,
        section: "Hero Section",
        heading: "Have Better Store Days.",
        subheading: "",
        text: "Retail is a daily grind—lines, stockouts, firefighting, late reports. iRipple helps retailers run smoother: faster checkout, clearer inventory, better decisions, tighter control. Better Store Days.",
        cta: "Schedule a Demo",
        media: "/images/home-hero.png",
        notes: "",
      },
      {
        order: 2.0,
        section: "Proof Bar",
        heading: "Trusted at scale by leading Southeast Asian retailers",
        subheading: "",
        text: "400+ retail brands served\n\n4,000+ stores managed\n\n10,000+ POS deployed\n\n1,000,000+ receipts printed per day\n\n25 years in retail tech",
        cta: "",
        media: "",
        notes: "Stat Blocks.\n\nDesign: big number + small label.",
      },
      {
        order: 3.0,
        section: "Clients & Trust",
        heading: "",
        subheading: "",
        text: "",
        cta: "",
        media: "",
        notes: "Logo strip of key clients",
      },
      {
        order: 4.0,
        section: "Built for the people who carry the store day",
        heading: "Built for every retail employee — from cashier to CEO",
        subheading: "",
        text: "Cashiers & Frontliners\nFaster lines. Fewer errors. Smoother shifts.\n\nInventory & Stockroom\nCleaner counts, faster movement, fewer stockouts.\n\nIT Managers\nDeploy upgrades with a single-click. Simplify data management.\n\nOperations & Executives\nBranch-by-branch clarity to drive action.",
        cta: "Discover Better Days",
        media: "",
        notes: "Panels (photo left, text right; alternating):\n",
      },
      {
        order: 5.0,
        section: "Product Highlights",
        heading: "Technology That Works Together",
        subheading: "",
        text: "Barter POS\nFast, reliable point-of-sale system. Process transactions smoothly even during peak hours and store-wide sales events.\n\nBarter Retail Management System\nCentralized control for multi-store operations. Manage inventory, pricing, promotions, and operations across all locations from a single dashboard.\n\nRetina Business Intelligence\nTurn transaction data into actionable insights. Real-time analytics and reporting that help you make better decisions about inventory, pricing, and operations.\n\nMyRewards Customer Loyalty\nBuild stronger customer relationships through rewards and personalized offers. Turn one-time shoppers into repeat customers with a loyalty program that actually works.\n\nAtlas Concessionaire App\nManage inventory right from the stockroom floor. Scan barcodes, update stock levels, process receiving, and perform cycle counts without being tied to a desktop.",
        cta: "Learn More",
        media:
          "Consistent device mockups (POS terminal + laptop dashboards + mobile screens).",
        notes:
          "5-card grid.  Cards with outcome-first blurbs and “Learn more” links:",
      },
      {
        order: 6.0,
        section: "What Better Store Days looks like",
        heading: "How store days get better",
        subheading: "",
        text: "Speed at the Frontline\nSmoother checkout, fewer disruptions, happier shoppers and staff.\n\nAvailability & Accuracy\nBetter on-shelf availability, cleaner inventory, tighter discipline.\n\nClarity for Managers\nReal-time visibility so leaders stop guessing and start deciding.\n\nImproved Loyalty\nShoppers become regulars.  Regulars become ambassadors.",
        cta: "",
        media:
          "Light icons per card + one supporting retail photo behind/near the grid.",
        notes: "Cards (each with 1–2 lines).",
      },
      {
        order: 7.0,
        section: "Contact / Demo",
        heading: "Let’s make your store days better.",
        subheading: "Fill-up the form or send us an email at sales@iripple.com",
        text: "",
        cta: "Schedule a Demo",
        media: "",
        notes: "",
      },
    ],
  },
  products: {
    id: "products",
    label: "Products",
    path: "/products",
    title: "Products",
    description:
      "Five integrated products that cover every aspect of modern retail operations. Choose what you need, scale as you grow.",
    sections: [
      {
        order: 1.0,
        section: "Products Hero",
        heading: "Technology That Works Together",
        subheading: "",
        text: "Five integrated products that cover every aspect of modern retail operations. Choose what you need, scale as you grow.",
        cta: "",
        media: "/images/tech-hero.png",
        notes: "",
      },
      {
        order: 2.0,
        section: "Product Cards",
        heading: "",
        subheading: "",
        text: "Barter POS\nFast, reliable point-of-sale system. Process transactions smoothly even during peak hours and store-wide sales events.\n\nBarter Retail Management System\nCentralized control for multi-store operations. Manage inventory, pricing, promotions, and operations across all locations from a single dashboard.\n\nRetina Business Intelligence\nTurn transaction data into actionable insights. Real-time analytics and reporting that help you make better decisions about inventory, pricing, and operations.\n\nMyRewards Customer Loyalty\nBuild stronger customer relationships through rewards and personalized offers. Turn one-time shoppers into repeat customers with a loyalty program that actually works.\n\nAtlas Concessionaire App\nManage inventory right from the stockroom floor. Scan barcodes, update stock levels, process receiving, and perform cycle counts without being tied to a desktop.",
        cta: "Learn More",
        media:
          "Consistent device mockups (POS terminal + laptop dashboards + mobile screens).",
        notes:
          "5-card grid.  Cards with outcome-first blurbs and “Learn more” links:",
      },
      {
        order: 3.0,
        section: "CTA band",
        heading: "Would you like to see these products in action?",
        subheading: "",
        text: "Schedule a Demo",
        cta: "",
        media: "",
        notes: "",
      },
    ],
  },
  "barter-pos": {
    id: "barter-pos",
    label: "Barter POS",
    path: "/products/barter-pos",
    title: "Barter POS",
    description: "POINT-OF-SALE SYSTEM",
    sections: [
      {
        order: 1.0,
        section: "Hero",
        heading: "Barter POS",
        subheading: "POINT-OF-SALE SYSTEM",
        text: "Fast, reliable checkout that keeps lines moving. Built to handle high-volume transactions during peak hours and promotional events without slowdowns or errors.",
        cta: "Request a Demo",
        media: "/images/products/1.png",
        notes: "",
      },
      {
        order: 2.0,
        section: "Benefits",
        heading: "Built for Speed and Accuracy",
        subheading:
          "Every feature designed to make checkout faster and reduce errors at the counter.",
        text: "Quick Product Lookup\nSearch by barcode, SKU, or product name. Fast scanning with instant price verification to keep checkout moving smoothly.\n\nMultiple Payment Methods\nAccept cash, card, e-wallets, and store credit. Process split payments and apply discounts without slowing down the line.\n\nPromotion Engine\nAutomatic discount application, buy-one-get-one deals, bundle pricing, and promotional codes that calculate correctly every time.\n\nOffline Mode\nContinue processing transactions even during internet outages. Transactions sync automatically when connection is restored.\n\nReturns and Exchanges\nProcess returns and exchanges quickly with proper audit trails. Verify purchase history and apply correct restocking policies.\n\nEnd-of-Day Reporting\nAutomatic cash drawer reconciliation, daily sales summaries, and shift reports for proper cash management and accountability.",
        cta: "",
        media: "",
        notes: "",
      },
      {
        order: 3.0,
        section: "CTA",
        heading: "Ready to Speed Up Checkout?",
        subheading:
          "See how Barter POS can reduce wait times and improve accuracy at your stores.",
        text: "",
        cta: "Schedule a Demo",
        media: "",
        notes: "",
      },
    ],
  },
  "barter-rms": {
    id: "barter-rms",
    label: "Barter RMS",
    path: "/products/barter-rms",
    title: "Barter RMS",
    description: "RETAIL MANAGEMENT SYSTEM",
    sections: [
      {
        order: 1.0,
        section: "Hero",
        heading: "Barter RMS",
        subheading: "RETAIL MANAGEMENT SYSTEM",
        text: "Centralized control for multi-store operations. Manage inventory, pricing, promotions, and operations across all locations from a single dashboard.",
        cta: "Request a Demo",
        media: "/images/products/2.png",
        notes: "",
      },
      {
        order: 2.0,
        section: "Benefits",
        heading: "Complete Operational Control",
        subheading:
          "Everything you need to manage multiple store locations from headquarters.",
        text: "Centralized Inventory Management\nTrack stock levels across all locations in real-time. Set reorder points, manage transfers, and prevent stockouts or overstock situations.\n\nPrice Management\nUpdate pricing across all stores or specific locations. Schedule price changes, manage markdown strategies, and maintain price consistency.\n\nSupplier Management\nTrack vendor performance, manage purchase orders, and monitor delivery schedules. Maintain accurate supplier information and terms.\n\nStore-to-Store Transfers\nBalance inventory between locations efficiently. Request, approve, and track transfers with full audit trails and documentation.\n\nPromotion Planning\nCreate and schedule promotional campaigns across stores. Set up discount rules, bundle offers, and loyalty rewards from a central system.\n\nUser Access Control\nDefine roles and permissions for different user levels. Control what each team member can access and modify across the system.",
        cta: "",
        media: "",
        notes: "",
      },
      {
        order: 3.0,
        section: "CTA",
        heading: "Ready for Centralized Control?",
        subheading:
          "See how Barter RMS can streamline multi-store management for your retail chain.",
        text: "",
        cta: "Schedule a Demo",
        media: "",
        notes: "",
      },
    ],
  },
  "retina-bi": {
    id: "retina-bi",
    label: "Retina Business Intelligence",
    path: "/products/retina-bi",
    title: "Retina Business Intelligence",
    description: "BUSINESS INTELLIGENCE",
    sections: [
      {
        order: 1.0,
        section: "Hero",
        heading: "Retina BI",
        subheading: "BUSINESS INTELLIGENCE",
        text: "Turn transaction data into actionable insights. Real-time analytics and reporting that help you make better decisions about inventory, pricing, and operations.",
        cta: "Request a Demo",
        media: "/images/products/3.png",
        notes: "",
      },
      {
        order: 2.0,
        section: "Benefits",
        heading: "Data-Driven Decision Making",
        subheading:
          "Understand your business performance with clear, actionable analytics.",
        text: "Real-Time Sales Dashboard\nMonitor sales performance as it happens. Track daily, weekly, and monthly trends across all stores and product categories.\n\nInventory Analytics\nIdentify slow-moving items, track turnover rates, and optimize stock levels. See which products are driving profitability.\n\nCustomer Behavior Analysis\nUnderstand purchase patterns, basket size, and repeat customer rates. Identify opportunities for cross-selling and upselling.\n\nStore Performance Comparison\nCompare metrics across locations to identify top performers and areas needing improvement. Benchmark against regional and chain averages.\n\nCustom Report Builder\nCreate reports tailored to your specific needs. Schedule automated reports and share insights with your team members.\n\nProfitability Analysis\nTrack gross margins by product, category, and store. Identify your most profitable items and optimize your product mix accordingly.",
        cta: "",
        media: "",
        notes: "",
      },
      {
        order: 3.0,
        section: "CTA",
        heading: "Ready for Better Insights?",
        subheading:
          "See how Retina BI can help you make smarter, data-driven business decisions.",
        text: "",
        cta: "Schedule a Demo",
        media: "",
        notes: "",
      },
    ],
  },
  "myrewards-loyalty": {
    id: "myrewards-loyalty",
    label: "MyRewards Loyalty",
    path: "/products/myrewards-loyalty",
    title: "MyRewards Loyalty",
    description: "CUSTOMER LOYALTY PLATFORM",
    sections: [
      {
        order: 1.0,
        section: "Hero",
        heading: "myRewards",
        subheading: "CUSTOMER LOYALTY PLATFORM",
        text: "Build stronger customer relationships through rewards and personalized offers. Turn one-time shoppers into repeat customers with a loyalty program that actually works.",
        cta: "Request a Demo",
        media: "/images/products/4.png",
        notes: "",
      },
      {
        order: 2.0,
        section: "Benefits",
        heading: "Loyalty That Drives Repeat Business",
        subheading:
          "Give customers reasons to come back and spend more with every visit.",
        text: "Points-Based Rewards\nCustomers earn points on every purchase. Simple, transparent earning rules that encourage repeat visits and higher basket sizes.\n\nTier-Based Benefits\nReward your best customers with VIP status, exclusive perks, and special pricing. Encourage customers to reach higher spending tiers.\n\nPersonalized Offers\nSend targeted promotions based on purchase history and preferences. Birthday rewards, anniversary offers, and personalized discounts.\n\nMobile App Integration\nCustomers can check points balance, browse rewards catalog, and redeem offers right from their phone. Push notifications for new offers.\n\nCampaign Management\nRun time-limited promotions, double-points days, and bonus point campaigns. Track campaign performance and ROI in real-time.\n\nMember Analytics\nUnderstand member behavior, redemption patterns, and program effectiveness. Identify your most valuable customers and engagement opportunities.",
        cta: "",
        media: "",
        notes: "",
      },
      {
        order: 3.0,
        section: "CTA",
        heading: "Ready to Build Customer Loyalty?",
        subheading:
          "See how myRewards can help you create lasting relationships with your customers.",
        text: "",
        cta: "Schedule a Demo",
        media: "",
        notes: "",
      },
    ],
  },
  "atlas-inventory-app": {
    id: "atlas-inventory-app",
    label: "Atlas Inventory App",
    path: "/products/atlas-inventory-app",
    title: "Atlas Inventory App",
    description: "MOBILE INVENTORY MANAGEMENT",
    sections: [
      {
        order: 1.0,
        section: "Hero",
        heading: "Atlas Mobile App",
        subheading: "MOBILE INVENTORY MANAGEMENT",
        text: "Manage inventory right from the stockroom floor. Scan barcodes, update stock levels, process receiving, and perform cycle counts without being tied to a desktop.",
        cta: "Request a Demo",
        media: "/images/products/5.png",
        notes: "",
      },
      {
        order: 2.0,
        section: "Benefits",
        heading: "Inventory Management, Untethered",
        subheading:
          "Handle stockroom operations efficiently with mobile-first tools.",
        text: "Barcode Scanning\nUse your phone's camera or connect a Bluetooth scanner. Quickly look up products, verify stock, and update quantities on the spot.\n\nReceiving and Put-Away\nProcess incoming deliveries directly from receiving area. Verify shipments against purchase orders and update inventory in real-time.\n\nCycle Counts\nPerform regular inventory counts without disrupting sales floor operations. Compare actual counts against system records and reconcile discrepancies.\n\nStock Adjustments\nRecord damaged items, shrinkage, and other inventory adjustments immediately. Maintain accurate records with proper reason codes.\n\nTransfer Processing\nPrepare and process store-to-store transfers. Scan items being transferred, verify quantities, and update both sending and receiving locations.\n\nOffline Functionality\nContinue working even without internet connection. All transactions sync automatically when connectivity is restored.",
        cta: "",
        media: "",
        notes: "",
      },
      {
        order: 3.0,
        section: "CTA",
        heading: "Ready for Mobile Inventory?",
        subheading:
          "See how Atlas can streamline your stockroom operations and improve inventory accuracy.",
        text: "",
        cta: "Schedule a Demo",
        media: "",
        notes: "",
      },
    ],
  },
  about: {
    id: "about",
    label: "About Us",
    path: "/about",
    title: "About Us",
    description:
      "iRipple partners with growing retailers to run smoother operations—built for Philippine retail realities and proven in the field.",
    sections: [
      {
        order: 1.0,
        section: "About Hero",
        heading: "We build systems that make store days better.",
        subheading: "",
        text: "iRipple partners with growing retailers to run smoother operations—built for South East Asian retail realities and proven in the field.",
        cta: "",
        media: "/images/about-hero.png",
        notes: "",
      },
      {
        order: 2.0,
        section: "About navigation cards",
        heading: "",
        subheading: "",
        text: "History\nHow we've grown from startup to serving thousands of stores across the Philippines, Malaysia, Thailand, and Papua New Guinea.\n\nMission & Vision\nOur purpose and where we're headed as we continue building better tools for South East Asian retailers.\n\nCore Values\nThe principles that guide how we build products, serve customers, and work together as a team.",
        cta: "Read More",
        media: "",
        notes: "3 cards linking to subpages",
      },
      {
        order: 3.0,
        section: "CTA band",
        heading: "Want to work with a team obsessed with store-day execution?",
        subheading: "",
        text: "",
        cta: "Talk to Sales",
        media: "",
        notes: "",
      },
    ],
  },
  history: {
    id: "history",
    label: "History",
    path: "/about/history",
    title: "History",
    description:
      "Built through years of real retail problems—store by store, shift by shift, branch by branch.",
    sections: [
      {
        order: 1.0,
        section: "Hero",
        heading: "Our story",
        subheading: "",
        text: "Built through years of solving real retail problems—store by store, shift by shift, branch by branch.",
        cta: "",
        media: "/images/history-hero.png",
        notes: "",
      },
      {
        order: 2.0,
        section: "Timeline (Vertical)",
        heading: "Our Journey",
        subheading: "",
        text: "2000 - 2005\nCollege classmates Victor Javier and Hubert Dy established iRipple in the Philippines in Nov 21, 2000 as a software development company.  Working off a garage, they created custom applications for clients. In 2002, they decided to focus solely on providing technology for the retail industry - leading to the creation of Barter POS, iRipple's core product.\n\n2006 - 2010\niRipple steadily grew and added major retailers like Suysing, Super 8, GABC (Penshoppe), and Primer – establishing iRipple as a major player in the local retail technology industry. Consequently, iRipple started to venture internationally.  In 2009, Imonggo, a software-as-a-service web-based POS was launched for the international SME Retail market. Imonggo is now used by retailers across 169 countries worldwide. Also in 2009, iRipple also became publicly listed on Philippine Stock Exchange.\n\n2011 - 2015\nThe continued success from Imonggo opened the possibility for iRipple to expand internationally. Taking Mydin (Malaysia), LME (Thailand) and Agmark (Papua New Guinea) part of its valued clients. In 2015, iRipple bought back its public shares to be a 100% privately owned local corporation. While pushing for international success, iRipple continued to expand locally in the Philippines by serving highly regarded clients like Prince Retail Group and Bonchon.\n\n2016 - 2020\niRipple expanded by incorporating  Hanrio - Hardware distribution company - to serve retail clients who want to have a single supplier for their software and hardware technology needs. Fernan Lukban, iRipple's current Chairman, joined in 2016, followed by CEO Ivan Lanuza in 2019, who also brought in Retina Business Intelligence platform. iRipple's offerings advanced into various retail tech solutions - including customer loyalty, business intelligence, and mobile inventory management.  Client base further expanded into new segments - bringing in Jetti (Gas Stations) and CW Home Depot (Hardlines). In 2019, Fernan, Victor, Ivan, and Hubert also founded MySuki - an FMCG supply chain digitization company.\n\n2021 - 2025\nDespite the headwinds brought about by the pandemic, iRipple further boosted their local presence by adding major retailers like CMG/Celine Group, Asian Home Appliances, and Shakey’s Group into its client base. iRipple also created its latest core offering: Barter XI - a full Retail Management Solution.  Allowing it to serve even larger enterprise clients. With an eye towards the future, iRipple continues to look for ways to bring about its vision of having retailers speed-up and scale-up through technology.",
        cta: "",
        media: "",
        notes: "",
      },
      {
        order: 3.0,
        section: "CTA",
        heading: "Let’s write the next chapter—together.",
        subheading: "",
        text: "",
        cta: "Schedule a Demo",
        media: "",
        notes: "",
      },
    ],
  },
  "core-values": {
    id: "core-values",
    label: "Core Values",
    path: "/about/core-values",
    title: "Core Values",
    description: "The habits behind reliable store-day execution.",
    sections: [
      {
        order: 1.0,
        section: "Core Values",
        heading: "Our Core Values",
        subheading: "",
        text: "The habits behind reliable store-day execution.",
        cta: "",
        media: "/images/corevalues.png",
        notes: "",
      },
      {
        order: 2.0,
        section: "Values grid",
        heading: "How we Think (Character)",
        subheading: "The mindsets that guide every decision before we act.",
        text: "Integrity\nDo the right thing, even when it costs.\n\nCustomer Obsession\nWe win when retailers win.\n\nPrudence\nServe smart, not just hard",
        cta: "",
        media: "",
        notes: "Create 3 columns with cluster headers and 3 value cards each.",
      },
      {
        order: 3.0,
        section: "Values grid",
        heading: "How we Move (Working Norms)",
        subheading: "The everyday pace and actions that create momentum.",
        text: "Boldness\nSay it, try it, own it, ask for help\n\nUrgency\nMove with energy and speed.\n\nAdaptability\nAdjust quickly to still deliver what was promised",
        cta: "",
        media: "",
        notes: "Create 3 columns with cluster headers and 3 value cards each.",
      },
      {
        order: 4.0,
        section: "Values grid",
        heading: "How we Win (Success Habits)",
        subheading: "The habits that turn plans into lasting results.",
        text: "Focus\nProtect the main thing from distractions.\n\nExcellence\nAim higher than yesterday.\n\nDiscipline\nFinish strong.",
        cta: "",
        media: "",
        notes: "Create 3 columns with cluster headers and 3 value cards each.",
      },
      {
        order: 5.0,
        section: "CTA",
        heading: "If we share these values, let's talk.",
        subheading: "",
        text: "",
        cta: "Schedule a Demo",
        media: "",
        notes: "",
      },
    ],
  },
  "mission-vision": {
    id: "mission-vision",
    label: "Mission and Vision",
    path: "/about/mission-vision",
    title: "Mission and Vision",
    description: "",
    sections: [
      {
        order: 1.0,
        section: "Mission",
        heading: "Mission: Lead retailers to greatness through technology.",
        subheading:
          "Better store days through systems that remove chaos and add clarity.",
        text: "",
        cta: "",
        media: "/images/mission.png",
        notes: "",
      },
      {
        order: 2.0,
        section: "Vision",
        heading:
          "Vision: Retailers can scale up and speed up using iRipple technology.",
        subheading:
          "From store operations to executive decisions—better every day.",
        text: "",
        cta: "",
        media: "/images/vision.png",
        notes: "",
      },
      {
        order: 4.0,
        section: "CTA band",
        heading:
          "If our mission is aligned with your ambition, we should talk.",
        subheading: "",
        text: "",
        cta: "Talk to Sales",
        media: "",
        notes: "",
      },
    ],
  },
  careers: {
    id: "careers",
    label: "Careers",
    path: "/careers",
    title: "Careers",
    description:
      "Join the team building mission-critical retail systems used in real stores, every day.",
    sections: [
      {
        order: 1.0,
        section: "Hero",
        heading: "Build Better Store Days—with us.",
        subheading: "",
        text: "Join the team building mission-critical retail systems used in real stores, every day.",
        cta: "",
        media: "/images/careers-hero.png",
        notes: "",
      },
      {
        order: 2.0,
        section: "Why iRipple",
        heading: "Why Work at iRipple",
        subheading: "",
        text: "Real-world problems that matter\nYour work directly helps Philippine retailers run better operations and serve their customers more effectively.\n\nRetail-scale systems and learning\nLearn from experienced team members, take on challenging and mission-critical projects, and advance your career in retail technology.\n\nCollaborative Culture\nWork with a team that values your ideas, supports your development, and celebrates wins together.\n\nBuild Locally, Deploy Globally\nBe part of the team that builds enteprise-grade retail systems used by stores across Southeast Asia and beyond.",
        cta: "",
        media: "",
        notes: "3 cards",
      },
      {
        order: 3.0,
        section: "Life at iRipple",
        heading: "What Our Employees Say",
        subheading: "",
        text: "“iRipple has mastered the art of work-life balance. We make it possible for you to grow, enjoy life, and succeed - all at the same time.“\n- Hubert Dy / Chief Technology Officer (25 years in iRipple)\n\n“I am able to use my talents and do work that I am proud of.”\n- Wil Anosa / Software Engineer (7 years in iRipple)\n\n“I trust my colleagues and I enjoy working with them.”\n- Meanne Prufer / Audit & Comp. Manager (18 years in iRipple)\n\n“I am able to grow and learn because I am given appropriate challenges and support.”\n- Pau Cabrera / VP for Client Engagements (11 years in iRipple)",
        cta: "",
        media: "",
        notes: "Quotes / culture cards",
      },
      {
        order: 4.0,
        section: "Open roles",
        heading: "",
        subheading: "",
        text: "",
        cta: "",
        media: "",
        notes: "Cards for open job positions",
      },
      {
        order: 5.0,
        section: "Hiring process",
        heading: "Hiring Process",
        subheading: "",
        text: "Apply by sending your CV to hr@iripple.com. → Have initial call with our recruitment officer. → Attend Technical/role interview with iRipple Employees. → Expect to hear from us in 1-2 weeks after your interview.",
        cta: "",
        media: "",
        notes: "",
      },
      {
        order: 6.0,
        section: "CTA band",
        heading: "If you care about real-world execution, you’ll fit here.",
        subheading: "",
        text: "",
        cta: "",
        media: "",
        notes: "",
      },
    ],
  },
};
