export const SITE = {
  name: "iRipple",
  primaryCta: "Schedule a Demo",
  salesCta: "Talk to Sales",
};

export const NAV = {
  main: [
    {
      label: "Home",
      path: "/",
    },
    {
      label: "Products",
      path: "/products",
    },
    {
      label: "About",
      path: "/about",
    },
    {
      label: "Careers",
      path: "/careers",
    },
  ],
  products: [
    {
      label: "Barter POS",
      path: "/products/barter-pos",
      id: "barter-pos",
    },
    {
      label: "Barter RMS",
      path: "/products/barter-rms",
      id: "barter-rms",
    },
    {
      label: "Retina Business Intelligence",
      path: "/products/retina-bi",
      id: "retina-bi",
    },
    {
      label: "MyRewards Loyalty",
      path: "/products/myrewards-loyalty",
      id: "myrewards-loyalty",
    },
    {
      label: "Atlas Inventory App",
      path: "/products/atlas-inventory-app",
      id: "atlas-inventory-app",
    },
  ],
  about: [
    {
      label: "History",
      path: "/about/history",
      id: "history",
    },
    {
      label: "Core Values",
      path: "/about/core-values",
      id: "core-values",
    },
    {
      label: "Mission and Vision",
      path: "/about/mission-vision",
      id: "mission-vision",
    },
  ],
};

export const PAGES = {
  home: {
    id: "home",
    label: "Home",
    path: "/",
    title: "Home",
    description:
      "Retail is a daily grind—lines, stockouts, firefighting, late reports. iRipple helps retailers run smoother days: faster checkout, clearer inventory, better d…",
    sections: [
      {
        order: 1.0,
        section: "Hero Section",
        heading: "Have Better Store Days.",
        subheading: "",
        text: "Retail is a daily grind—lines, stockouts, firefighting, late reports. iRipple helps retailers run smoother: faster checkout, clearer inventory, better decisions, tighter control. Better Store Days.",
        cta: "Schedule a Demo",
        media: "/images/home-hero.png",
        notes: "",
      },
      {
        order: 2.0,
        section: "Proof Bar",
        heading: "Trusted at scale by leading Southeast Asian retailers",
        subheading: "",
        text: "1,000,000+ receipts printed per day\n\n10,000+ POS deployed\n\n4,000+ stores managed\n\n400+ retail brands served\n\n25 years in retail tech",
        cta: "",
        media: "",
        notes: "Stat Blocks.\n\nDesign: big number + small label.",
      },
      {
        order: 3.0,
        section: "Clients & Trust",
        heading: "",
        subheading: "",
        text: "",
        cta: "",
        media: "",
        notes: "Logo strip of key clients",
      },
      {
        order: 4.0,
        section: "Built for the people who carry the store day",
        heading: "Built for every retail employee — from cashier to CEO",
        subheading: "",
        text: "Cashiers & Frontliners\nFaster lines, fewer errors, and smoother shifts.\n\nMarketing Creatives\nKnow your customers. Launch promotions faster.\n\nMerchandisers\nRight Items. Right Price. Right promos. Right Inventory.\n\nIT Managers\nDeploy upgrades in one-click. Stress less about BIR & Mall requirements.\n\nStore Operations\nSmoother stores. Faster coaching. Cleaner execution.\n\nExecutives\nClarity across the business. Faster decisions. Better profit.",
        cta: "Learn More",
        media: "",
        notes: "Panels (photo left, text right; alternating):\n",
      },
      {
        order: 5.0,
        section: "Product Highlights",
        heading: "Technology For Better Store Days",
        subheading: "",
        text: "Barter POS\nFast, reliable point-of-sale system. Process transactions smoothly even during peak hours and store-wide sales events.\n\nBarter Retail Management System\nCentralized control for multi-store operations. Manage inventory, pricing, promotions, and operations across all locations from a single dashboard.\n\nRetina Business Intelligence\nTurn transaction data into actionable insights. Real-time analytics and reporting that help you make better decisions about inventory, pricing, and operations.\n\nMyRewards Customer Loyalty\nBuild stronger customer relationships through rewards and personalized offers. Turn one-time shoppers into repeat customers with a loyalty program that actually works.\n\nAtlas Concessionaire App\nManage inventory right from the stockroom floor. Scan barcodes, update stock levels, process receiving, and perform cycle counts without being tied to a desktop.",
        cta: "Learn More",
        media:
          "Consistent device mockups (POS terminal + laptop dashboards + mobile screens).",
        notes:
          "5-card grid.  Cards with outcome-first blurbs and “Learn more” links:",
      },
      {
        order: 6.0,
        section: "Contact / Demo",
        heading: "Let’s make your store days better.",
        subheading: "Fill-up the form or send us an email at sales@iripple.com",
        text: "",
        cta: "Schedule a Demo",
        media: "",
        notes: "",
      },
    ],
  },
  products: {
    id: "products",
    label: "Products",
    path: "/products",
    title: "Products",
    description:
      "Five integrated products that cover every aspect of modern retail operations. Choose what you need, scale as you grow.",
    sections: [
      {
        order: 1.0,
        section: "Products Hero",
        heading: "Technology For Better Store Days",
        subheading: "",
        text: "Five integrated products that cover every aspect of modern retail operations. Choose what you need, scale as you grow.",
        cta: "",
        media: "/images/tech-hero.png",
        notes: "",
      },
      {
        order: 2.0,
        section: "Product Cards",
        heading: "",
        subheading: "",
        text: "Barter POS\nFast, reliable point-of-sale system. Process transactions smoothly even during peak hours and store-wide sales events.\n\nBarter Retail Management System\nCentralized control for multi-store operations. Manage inventory, pricing, promotions, and operations across all locations from a single dashboard.\n\nRetina Business Intelligence\nTurn transaction data into actionable insights. Real-time analytics and reporting that help you make better decisions about inventory, pricing, and operations.\n\nMyRewards Customer Loyalty\nBuild stronger customer relationships through rewards and personalized offers. Turn one-time shoppers into repeat customers with a loyalty program that actually works.\n\nAtlas Concessionaire App\nManage inventory right from the stockroom floor. Scan barcodes, update stock levels, process receiving, and perform cycle counts without being tied to a desktop.",
        cta: "Learn More",
        media:
          "Consistent device mockups (POS terminal + laptop dashboards + mobile screens).",
        notes:
          "5-card grid.  Cards with outcome-first blurbs and “Learn more” links:",
      },
      {
        order: 3.0,
        section: "CTA band",
        heading: "Would you like to see these products in action?",
        subheading: "",
        text: "Schedule a Demo",
        cta: "",
        media: "",
        notes: "",
      },
    ],
  },
  "barter-pos": {
    id: "barter-pos",
    label: "Barter POS",
    path: "/products/barter-pos",
    title: "Barter POS",
    description: "POINT-OF-SALE SYSTEM",
    sections: [
      {
        order: 1.0,
        section: "Hero",
        heading: "Barter POS",
        subheading: "POINT-OF-SALE SYSTEM",
        text: "Fast, reliable checkout that keeps lines moving. Built to handle high-volume transactions during peak hours and promotional events without slowdowns or errors.",
        cta: "Request a Demo",
        media: "/images/products/1.png",
        notes: "",
      },
      {
        order: 2.0,
        section: "Benefits",
        heading: "Built for Speed and Accuracy",
        subheading:
          "Every feature designed to make checkout faster and reduce errors at the counter.",
        text: "Quick Product Lookup\nSearch by barcode, SKU, or product name. Fast scanning with instant price verification to keep checkout moving smoothly.\n\nMultiple Payment Methods\nAccept cash, card, e-wallets, and store credit. Process split payments and apply discounts without slowing down the line.\n\nPromotion Engine\nAutomatic discount application, buy-one-get-one deals, bundle pricing, and promotional codes that calculate correctly every time.\n\nOffline Mode\nContinue processing transactions even during internet outages. Transactions sync automatically when connection is restored.\n\nReturns and Exchanges\nProcess returns and exchanges quickly with proper audit trails. Verify purchase history and apply correct restocking policies.\n\nEnd-of-Day Reporting\nAutomatic cash drawer reconciliation, daily sales summaries, and shift reports for proper cash management and accountability.",
        cta: "",
        media: "",
        notes: "",
      },
      {
        order: 3.0,
        section: "CTA",
        heading: "Ready to Speed Up Checkout?",
        subheading:
          "See how Barter POS can reduce wait times and improve accuracy at your stores.",
        text: "",
        cta: "Schedule a Demo",
        media: "",
        notes: "",
      },
    ],
  },
  "barter-rms": {
    id: "barter-rms",
    label: "Barter RMS",
    path: "/products/barter-rms",
    title: "Barter RMS",
    description: "RETAIL MANAGEMENT SYSTEM",
    sections: [
      {
        order: 1.0,
        section: "Hero",
        heading: "Barter RMS",
        subheading: "RETAIL MANAGEMENT SYSTEM",
        text: "Centralized control for multi-store operations. Manage inventory, pricing, promotions, and operations across all locations from a single dashboard.",
        cta: "Request a Demo",
        media: "/images/products/2.png",
        notes: "",
      },
      {
        order: 2.0,
        section: "Benefits",
        heading: "Complete Operational Control",
        subheading:
          "Everything you need to manage multiple store locations from headquarters.",
        text: "Centralized Inventory Management\nTrack stock levels across all locations in real-time. Set reorder points, manage transfers, and prevent stockouts or overstock situations.\n\nPrice Management\nUpdate pricing across all stores or specific locations. Schedule price changes, manage markdown strategies, and maintain price consistency.\n\nSupplier Management\nTrack vendor performance, manage purchase orders, and monitor delivery schedules. Maintain accurate supplier information and terms.\n\nStore-to-Store Transfers\nBalance inventory between locations efficiently. Request, approve, and track transfers with full audit trails and documentation.\n\nPromotion Planning\nCreate and schedule promotional campaigns across stores. Set up discount rules, bundle offers, and loyalty rewards from a central system.\n\nUser Access Control\nDefine roles and permissions for different user levels. Control what each team member can access and modify across the system.",
        cta: "",
        media: "",
        notes: "",
      },
      {
        order: 3.0,
        section: "CTA",
        heading: "Ready for Centralized Control?",
        subheading:
          "See how Barter RMS can streamline multi-store management for your retail chain.",
        text: "",
        cta: "Schedule a Demo",
        media: "",
        notes: "",
      },
    ],
  },
  "retina-bi": {
    id: "retina-bi",
    label: "Retina Business Intelligence",
    path: "/products/retina-bi",
    title: "Retina Business Intelligence",
    description: "BUSINESS INTELLIGENCE",
    sections: [
      {
        order: 1.0,
        section: "Hero",
        heading: "Retina BI",
        subheading: "BUSINESS INTELLIGENCE",
        text: "Turn transaction data into actionable insights. Real-time analytics and reporting that help you make better decisions about inventory, pricing, and operations.",
        cta: "Request a Demo",
        media: "/images/products/3.png",
        notes: "",
      },
      {
        order: 2.0,
        section: "Benefits",
        heading: "Data-Driven Decision Making",
        subheading:
          "Understand your business performance with clear, actionable analytics.",
        text: "Real-Time Sales Dashboard\nMonitor sales performance as it happens. Track daily, weekly, and monthly trends across all stores and product categories.\n\nInventory Analytics\nIdentify slow-moving items, track turnover rates, and optimize stock levels. See which products are driving profitability.\n\nCustomer Behavior Analysis\nUnderstand purchase patterns, basket size, and repeat customer rates. Identify opportunities for cross-selling and upselling.\n\nStore Performance Comparison\nCompare metrics across locations to identify top performers and areas needing improvement. Benchmark against regional and chain averages.\n\nCustom Report Builder\nCreate reports tailored to your specific needs. Schedule automated reports and share insights with your team members.\n\nProfitability Analysis\nTrack gross margins by product, category, and store. Identify your most profitable items and optimize your product mix accordingly.",
        cta: "",
        media: "",
        notes: "",
      },
      {
        order: 3.0,
        section: "CTA",
        heading: "Ready for Better Insights?",
        subheading:
          "See how Retina BI can help you make smarter, data-driven business decisions.",
        text: "",
        cta: "Schedule a Demo",
        media: "",
        notes: "",
      },
    ],
  },
  "myrewards-loyalty": {
    id: "myrewards-loyalty",
    label: "MyRewards Loyalty",
    path: "/products/myrewards-loyalty",
    title: "MyRewards Loyalty",
    description: "CUSTOMER LOYALTY PLATFORM",
    sections: [
      {
        order: 1.0,
        section: "Hero",
        heading: "myRewards",
        subheading: "CUSTOMER LOYALTY PLATFORM",
        text: "Build stronger customer relationships through rewards and personalized offers. Turn one-time shoppers into repeat customers with a loyalty program that actually works.",
        cta: "Request a Demo",
        media: "/images/products/4.png",
        notes: "",
      },
      {
        order: 2.0,
        section: "Benefits",
        heading: "Loyalty That Drives Repeat Business",
        subheading:
          "Give customers reasons to come back and spend more with every visit.",
        text: "Points-Based Rewards\nCustomers earn points on every purchase. Simple, transparent earning rules that encourage repeat visits and higher basket sizes.\n\nTier-Based Benefits\nReward your best customers with VIP status, exclusive perks, and special pricing. Encourage customers to reach higher spending tiers.\n\nPersonalized Offers\nSend targeted promotions based on purchase history and preferences. Birthday rewards, anniversary offers, and personalized discounts.\n\nMobile App Integration\nCustomers can check points balance, browse rewards catalog, and redeem offers right from their phone. Push notifications for new offers.\n\nCampaign Management\nRun time-limited promotions, double-points days, and bonus point campaigns. Track campaign performance and ROI in real-time.\n\nMember Analytics\nUnderstand member behavior, redemption patterns, and program effectiveness. Identify your most valuable customers and engagement opportunities.",
        cta: "",
        media: "",
        notes: "",
      },
      {
        order: 3.0,
        section: "CTA",
        heading: "Ready to Build Customer Loyalty?",
        subheading:
          "See how myRewards can help you create lasting relationships with your customers.",
        text: "",
        cta: "Schedule a Demo",
        media: "",
        notes: "",
      },
    ],
  },
  "atlas-inventory-app": {
    id: "atlas-inventory-app",
    label: "Atlas Inventory App",
    path: "/products/atlas-inventory-app",
    title: "Atlas Inventory App",
    description: "MOBILE INVENTORY MANAGEMENT",
    sections: [
      {
        order: 1.0,
        section: "Hero",
        heading: "Atlas Mobile App",
        subheading: "MOBILE INVENTORY MANAGEMENT",
        text: "Manage inventory right from the stockroom floor. Scan barcodes, update stock levels, process receiving, and perform cycle counts without being tied to a desktop.",
        cta: "Request a Demo",
        media: "/images/products/5.png",
        notes: "",
      },
      {
        order: 2.0,
        section: "Benefits",
        heading: "Inventory Management, Untethered",
        subheading:
          "Handle stockroom operations efficiently with mobile-first tools.",
        text: "Barcode Scanning\nUse your phone's camera or connect a Bluetooth scanner. Quickly look up products, verify stock, and update quantities on the spot.\n\nReceiving and Put-Away\nProcess incoming deliveries directly from receiving area. Verify shipments against purchase orders and update inventory in real-time.\n\nCycle Counts\nPerform regular inventory counts without disrupting sales floor operations. Compare actual counts against system records and reconcile discrepancies.\n\nStock Adjustments\nRecord damaged items, shrinkage, and other inventory adjustments immediately. Maintain accurate records with proper reason codes.\n\nTransfer Processing\nPrepare and process store-to-store transfers. Scan items being transferred, verify quantities, and update both sending and receiving locations.\n\nOffline Functionality\nContinue working even without internet connection. All transactions sync automatically when connectivity is restored.",
        cta: "",
        media: "",
        notes: "",
      },
      {
        order: 3.0,
        section: "CTA",
        heading: "Ready for Mobile Inventory?",
        subheading:
          "See how Atlas can streamline your stockroom operations and improve inventory accuracy.",
        text: "",
        cta: "Schedule a Demo",
        media: "",
        notes: "",
      },
    ],
  },
  about: {
    id: "about",
    label: "About Us",
    path: "/about",
    title: "About Us",
    description:
      "iRipple partners with growing retailers to run smoother operations—built for Philippine retail realities and proven in the field.",
    sections: [
      {
        order: 1.0,
        section: "About Hero",
        heading: "We build systems that make store days better.",
        subheading: "",
        text: "iRipple partners with growing retailers to run smoother operations—built for South East Asian retail realities and proven in the field.",
        cta: "",
        media: "/images/about-hero.png",
        notes: "",
      },
      {
        order: 2.0,
        section: "Timeline (Vertical)",
        heading: "Our Journey",
        subheading:
          "From startup to serving thousands of stores across the Philippines, Malaysia, Thailand, and Papua New Guinea.",
        text: "2000 - 2005\nCollege classmates Victor Javier and Hubert Dy established iRipple in the Philippines in Nov 21, 2000 as a software development company.  Working off a garage, they created custom applications for clients. In 2002, they decided to focus solely on providing technology for the retail industry - leading to the creation of Barter POS, iRipple's core product.\n\n2006 - 2010\niRipple steadily grew and added major retailers like Suysing, Super 8, GABC (Penshoppe), and Primer – establishing iRipple as a major player in the local retail technology industry. Consequently, iRipple started to venture internationally.  In 2009, Imonggo, a software-as-a-service web-based POS was launched for the international SME Retail market. Imonggo is now used by retailers across 169 countries worldwide. Also in 2009, iRipple also became publicly listed on Philippine Stock Exchange.\n\n2011 - 2015\nThe continued success from Imonggo opened the possibility for iRipple to expand internationally. Taking Mydin (Malaysia), LME (Thailand) and Agmark (Papua New Guinea) part of its valued clients. In 2015, iRipple bought back its public shares to be a 100% privately owned local corporation. While pushing for international success, iRipple continued to expand locally in the Philippines by serving highly regarded clients like Prince Retail Group and Bonchon.\n\n2016 - 2020\niRipple expanded by incorporating  Hanrio - Hardware distribution company - to serve retail clients who want to have a single supplier for their software and hardware technology needs. Fernan Lukban, iRipple's current Chairman, joined in 2016, followed by CEO Ivan Lanuza in 2019, who also brought in Retina Business Intelligence platform. iRipple's offerings advanced into various retail tech solutions - including customer loyalty, business intelligence, and mobile inventory management.  Client base further expanded into new segments - bringing in Jetti (Gas Stations) and CW Home Depot (Hardlines). In 2019, Fernan, Victor, Ivan, and Hubert also founded MySuki - an FMCG supply chain digitization company.\n\n2021 - 2025\nDespite the headwinds brought about by the pandemic, iRipple further boosted their local presence by adding major retailers like CMG/Celine Group, Asian Home Appliances, and Shakey’s Group into its client base. iRipple also created its latest core offering: Barter XI - a full Retail Management Solution.  Allowing it to serve even larger enterprise clients. With an eye towards the future, iRipple continues to look for ways to bring about its vision of having retailers speed-up and scale-up through technology.",
        cta: "",
        media: "",
        notes: "",
      },
      {
        order: 3.0,
        section: "Mission",
        heading: "Our Mission",
        subheading: "Lead retailers to greatness through technology.",
        text: "",
        cta: "",
        media: "/images/mission.png",
        notes: "",
      },
      {
        order: 4.0,
        section: "Vision",
        heading: "Our Vision",
        subheading:
          "Retailers can scale up and speed up using iRipple technology.",
        text: "",
        cta: "",
        media: "/images/vision.png",
        notes: "",
      },
      /*
      {
        order: 5.0,
        section: "About navigation cards",
        heading: "",
        subheading: "",
        text: "History\nHow we've grown from startup to serving thousands of stores across the Philippines, Malaysia, Thailand, and Papua New Guinea.\n\nMission & Vision\nOur purpose and where we're headed as we continue building better tools for South East Asian retailers.\n\nCore Values\nThe principles that guide how we build products, serve customers, and work together as a team.",
        cta: "Read More",
        media: "",
        notes: "3 cards linking to subpages",
      },
    */
      {
        order: 6.0,
        section: "Core Values",
        heading: "Our Core Values",
        subheading: "The habits behind reliable store-day execution.",
        text: "Our core values are the habits behind reliable store-day execution. They guide how we show up every day—how we think, how we move, and how we win—so we can consistently deliver what retailers need with clarity, speed, and accountability.\nIn how we think (Character), we lead with Integrity, doing the right thing even when it costs; Customer Obsession, believing we only win when retailers win; and Prudence, serving smart and making decisions that are sustainable, not just hardworking.\nIn how we move (Working Norms), we practice Boldness by saying what needs to be said, trying new things, owning outcomes, and asking for help when needed; Urgency by moving with energy and speed; and Adaptability by adjusting quickly while still delivering what was promised.\nAnd in how we win (Success Habits), we hold to Focus, protecting the main thing from distractions; Excellence, aiming higher than yesterday; and Discipline, finishing strong. ",
        cta: "",
        media: "/images/corevalues.png",
        notes: "",
      },

      {
        order: 6.0,
        section: "CTA band",
        heading: "Want to work with a team obsessed with store-day execution?",
        subheading: "",
        text: "",
        cta: "Talk to Sales",
        media: "",
        notes: "",
      },
    ],
  },
  history: {
    id: "history",
    label: "History",
    path: "/about/history",
    title: "History",
    description:
      "Built through years of real retail problems—store by store, shift by shift, branch by branch.",
    sections: [
      {
        order: 1.0,
        section: "Hero",
        heading: "Our story",
        subheading: "",
        text: "Built through years of solving real retail problems—store by store, shift by shift, branch by branch.",
        cta: "",
        media: "/images/history-hero.png",
        notes: "",
      },
      {
        order: 2.0,
        section: "Timeline (Vertical)",
        heading: "Our Journey",
        subheading: "",
        text: "2000 - 2005\nCollege classmates Victor Javier and Hubert Dy established iRipple in the Philippines in Nov 21, 2000 as a software development company.  Working off a garage, they created custom applications for clients. In 2002, they decided to focus solely on providing technology for the retail industry - leading to the creation of Barter POS, iRipple's core product.\n\n2006 - 2010\niRipple steadily grew and added major retailers like Suysing, Super 8, GABC (Penshoppe), and Primer – establishing iRipple as a major player in the local retail technology industry. Consequently, iRipple started to venture internationally.  In 2009, Imonggo, a software-as-a-service web-based POS was launched for the international SME Retail market. Imonggo is now used by retailers across 169 countries worldwide. Also in 2009, iRipple also became publicly listed on Philippine Stock Exchange.\n\n2011 - 2015\nThe continued success from Imonggo opened the possibility for iRipple to expand internationally. Taking Mydin (Malaysia), LME (Thailand) and Agmark (Papua New Guinea) part of its valued clients. In 2015, iRipple bought back its public shares to be a 100% privately owned local corporation. While pushing for international success, iRipple continued to expand locally in the Philippines by serving highly regarded clients like Prince Retail Group and Bonchon.\n\n2016 - 2020\niRipple expanded by incorporating  Hanrio - Hardware distribution company - to serve retail clients who want to have a single supplier for their software and hardware technology needs. Fernan Lukban, iRipple's current Chairman, joined in 2016, followed by CEO Ivan Lanuza in 2019, who also brought in Retina Business Intelligence platform. iRipple's offerings advanced into various retail tech solutions - including customer loyalty, business intelligence, and mobile inventory management.  Client base further expanded into new segments - bringing in Jetti (Gas Stations) and CW Home Depot (Hardlines). In 2019, Fernan, Victor, Ivan, and Hubert also founded MySuki - an FMCG supply chain digitization company.\n\n2021 - 2025\nDespite the headwinds brought about by the pandemic, iRipple further boosted their local presence by adding major retailers like CMG/Celine Group, Asian Home Appliances, and Shakey’s Group into its client base. iRipple also created its latest core offering: Barter XI - a full Retail Management Solution.  Allowing it to serve even larger enterprise clients. With an eye towards the future, iRipple continues to look for ways to bring about its vision of having retailers speed-up and scale-up through technology.",
        cta: "",
        media: "",
        notes: "",
      },
      {
        order: 5.0,
        section: "CTA",
        heading: "Let’s write the next chapter—together.",
        subheading: "",
        text: "",
        cta: "Schedule a Demo",
        media: "",
        notes: "",
      },
    ],
  },
  "core-values": {
    id: "core-values",
    label: "Core Values",
    path: "/about/core-values",
    title: "Core Values",
    description: "The habits behind reliable store-day execution.",
    sections: [
      {
        order: 1.0,
        section: "Core Values",
        heading: "Our Core Values",
        subheading: "",
        text: "The habits behind reliable store-day execution.",
        cta: "",
        media: "/images/corevalues.png",
        notes: "",
      },
      {
        order: 2.0,
        section: "Values grid",
        heading: "How we Think (Character)",
        subheading: "The mindsets that guide every decision before we act.",
        text: "Integrity\nDo the right thing, even when it costs.\n\nCustomer Obsession\nWe win when retailers win.\n\nPrudence\nServe smart, not just hard",
        cta: "",
        media: "",
        notes: "Create 3 columns with cluster headers and 3 value cards each.",
      },
      {
        order: 3.0,
        section: "Values grid",
        heading: "How we Move (Working Norms)",
        subheading: "The everyday pace and actions that create momentum.",
        text: "Boldness\nSay it, try it, own it, ask for help\n\nUrgency\nMove with energy and speed.\n\nAdaptability\nAdjust quickly to still deliver what was promised",
        cta: "",
        media: "",
        notes: "Create 3 columns with cluster headers and 3 value cards each.",
      },
      {
        order: 4.0,
        section: "Values grid",
        heading: "How we Win (Success Habits)",
        subheading: "The habits that turn plans into lasting results.",
        text: "Focus\nProtect the main thing from distractions.\n\nExcellence\nAim higher than yesterday.\n\nDiscipline\nFinish strong.",
        cta: "",
        media: "",
        notes: "Create 3 columns with cluster headers and 3 value cards each.",
      },
      {
        order: 5.0,
        section: "CTA",
        heading: "If we share these values, let's talk.",
        subheading: "",
        text: "",
        cta: "Schedule a Demo",
        media: "",
        notes: "",
      },
    ],
  },
  "mission-vision": {
    id: "mission-vision",
    label: "Mission and Vision",
    path: "/about/mission-vision",
    title: "Mission and Vision",
    description: "",
    sections: [
      {
        order: 1.0,
        section: "Mission",
        heading: "Mission: Lead retailers to greatness through technology.",
        subheading:
          "Better store days through systems that remove chaos and add clarity.",
        text: "",
        cta: "",
        media: "/images/mission.png",
        notes: "",
      },
      {
        order: 2.0,
        section: "Vision",
        heading:
          "Vision: Retailers can scale up and speed up using iRipple technology.",
        subheading:
          "From store operations to executive decisions—better every day.",
        text: "",
        cta: "",
        media: "/images/vision.png",
        notes: "",
      },
      {
        order: 4.0,
        section: "CTA band",
        heading:
          "If our mission is aligned with your ambition, we should talk.",
        subheading: "",
        text: "",
        cta: "Talk to Sales",
        media: "",
        notes: "",
      },
    ],
  },
  careers: {
    id: "careers",
    label: "Careers",
    path: "/careers",
    title: "Careers",
    description:
      "Join the team building mission-critical retail systems used in real stores, every day.",
    sections: [
      {
        order: 1.0,
        section: "Hero",
        heading: "Build Better Store Days—with us.",
        subheading: "",
        text: "Join the team building mission-critical retail systems used in real stores, every day.",
        cta: "",
        media: "/images/careers-hero.png",
        notes: "",
      },
      {
        order: 2.0,
        section: "Why iRipple",
        heading: "Why Work at iRipple",
        subheading: "",
        text: "Real-world problems that matter\nYour work directly helps Philippine retailers run better operations and serve their customers more effectively.\n\nRetail-scale systems and learning\nLearn from experienced team members, take on challenging and mission-critical projects, and advance your career in retail technology.\n\nCollaborative Culture\nWork with a team that values your ideas, supports your development, and celebrates wins together.\n\nBuild Locally, Deploy Globally\nBe part of the team that builds enteprise-grade retail systems used by stores across Southeast Asia and beyond.",
        cta: "",
        media: "",
        notes: "3 cards",
      },
      {
        order: 3.0,
        section: "Life at iRipple",
        heading: "What Our Employees Say",
        subheading: "",
        text: "“iRipple has mastered the art of work-life balance. We make it possible for you to grow, enjoy life, and succeed - all at the same time.“\n- Hubert Dy / Chief Technology Officer (25 years in iRipple)\n\n“I am able to use my talents and do work that I am proud of.”\n- Wil Anosa / Software Engineer (7 years in iRipple)\n\n“I trust my colleagues and I enjoy working with them.”\n- Meanne Prufer / Audit & Comp. Manager (18 years in iRipple)\n\n“I am able to grow and learn because I am given appropriate challenges and support.”\n- Pau Cabrera / VP for Client Engagements (11 years in iRipple)",
        cta: "",
        media: "",
        notes: "Quotes / culture cards",
      },
      {
        order: 4.0,
        section: "Open roles",
        heading: "",
        subheading: "",
        text: "",
        cta: "",
        media: "",
        notes: "Cards for open job positions",
      },
      {
        order: 5.0,
        section: "Hiring process",
        heading: "Hiring Process",
        subheading: "",
        text: "Apply by sending your CV to hr@iripple.com. → Have initial call with our recruitment officer. → Attend Technical/role interview with iRipple Employees. → Expect to hear from us in 1-2 weeks after your interview.",
        cta: "",
        media: "",
        notes: "",
      },
      {
        order: 6.0,
        section: "CTA band",
        heading: "If you care about real-world execution, you’ll fit here.",
        subheading: "",
        text: "",
        cta: "",
        media: "",
        notes: "",
      },
    ],
  },
  cashiers: {
    id: "cashiers",
    label: "Cashiers and Frontliners",
    path: "/retailroles/cashiers",
    title: "Cashiers and Frontliners",
    description: "CASHIERS AND FRONTLINERS",
    sections: [
      {
        order: 1.0,
        section: "Hero",
        heading: "Cashiers and Frontliners",
        subheading: "Faster lines. Fewer errors. Smoother shifts.",
        text: "Move lines faster with quick scanning and fewer price checks. Stay productive even offline, recover instantly after power interruptions, and let promos, loyalty, and split payments apply automatically—so every shift feels lighter.",
        cta: "Request a Demo",
        media: "/images/retailroles/cashiers.png",
        notes: "",
      },
      {
        order: 2.0,
        section: "Benefits",
        heading: "Built for Speed, Control, and Continuity",
        subheading:
          "Everything cashiers and frontliners need to scan fast, avoid mistakes, and stay productive—even when things go wrong.",
        text: "Reports that match the way you work\nGenerate end-of-day (EoD) reports, shift reports, cashier reports, and sales reports in seconds—so reconciliation and handover are clean and fast.\n\nOffline POS you can trust\nKeep selling even when the internet is down. Continue ringing up transactions with full functionality in offline mode.\n\nAuto-sync for always-correct data\nAutomatically sync to the latest version and pull updated product and pricing data—so cashiers always use the right SKU, price, and promo rules.\n\nBuilt-in controls and overrides\nRole-based controls for sensitive actions. Require supervisor override for voids, refunds, discounts, and other exceptions to reduce losses and prevent abuse.\n\nRecover transactions after power interruption\nRetrieve and continue orders even after sudden power loss—so long lines don’t turn into lost sales.\n\nFast scanning, 24/7 performance\nOptimized for high-speed barcode scanning and always-on store operations—built for peak hours and promo traffic.\n\nWeighted items, handled correctly\nSupport weighed goods (by weight/price) for fresh items—accurate totals with less manual entry.\n\nComplex promotions applied automatically\nHandle thousands of complex promos (bundles, mix-and-match, tiered discounts, BOGO, conditions) without cashier guesswork.\n\nLoyalty perks applied automatically\nAuto-apply customer loyalty rewards, discounts, and perks at checkout—faster lines and happier customers.\n\nPayments that settle cleanly\nIntegrate with popular payment channels for auto-settlement. Support multi-tender in a single transaction (cash + e-wallet + card, etc.) without delays.",
        cta: "",
        media: "",
        notes: "",
      },
      {
        order: 3.0,
        section: "CTA",
        heading: "Ready to give your frontliners better store days?",
        subheading: "",
        text: "",
        cta: "Schedule a Demo",
        media: "",
        notes: "",
      },
    ],
  },
  itmanagers: {
    id: "itManagers",
    label: "IT Managers",
    path: "/retailroles/it-managers",
    title: "IT Managers",
    description: "IT MANAGERS",
    sections: [
      {
        order: 1.0,
        section: "Hero",
        heading: "IT Managers",
        subheading: "Fewer fires. Faster rollouts. Clearer control.",
        text: "Standardize stores without the 2AM calls. Roll out upgrades centrally, monitor peripherals remotely, and keep compliance, security, and uptime under control across every branch.",
        cta: "Request a Demo",
        media: "/images/retailroles/itmanagers.png",
        notes: "",
      },
      {
        order: 2.0,
        section: "Benefits",
        heading: "Built for Central Control and Compliance",
        subheading:
          "Tools that reduce manual work, prevent outages, and make audits and rollouts predictable.",
        text: "Centralized version upgrades\nDeploy POS version upgrades across all stores in one go—no more one-by-one remote sessions.\n\nBuilt-in monitoring of peripherals\nView POS peripherals status (printers, scanners, drawers, displays) to spot issues early and reduce store downtime.\n\nCentral reporting for Z-readings\nGet a consolidated view of store Z-readings for faster reconciliation, audit readiness, and visibility across branches.\n\nCentralized user management\nCreate, update, and revoke users and roles centrally—consistent access control across all stores.\n\nBIR accreditation and compliance\nDon't stress about BIR accreditation and registration - iRipple ensures you stay compliant and up-to-date.\n\nMall accreditation and compliance\nMeet mall IT and reporting requirements.  iRipple POS is accredited in all major malls of the country.\n\nDedicated support team with ticketing\nRoute issues through a ticketing system with clear ownership, tracking, and faster resolution.\n\nRegular feature releases\nGet ongoing improvements and new capabilities through regular releases—without disruptive store-by-store upgrades.\n\nFull cloud management\nCloud performance monitoring, security controls, and data redundancy/backups to reduce operational risk and improve uptime.\n\nOpenAPI option for custom integrations\nOptional OpenAPI access so you can build custom extensions or integrate internal tools on top of iRipple platforms.\n\nData dumps to S3 for external warehousing\nOption to push data dumps to an S3 bucket so your BI/data team can load to an external data warehouse.",
        cta: "",
        media: "",
        notes: "",
      },
      {
        order: 3.0,
        section: "CTA",
        heading: "Ready to make retail IT more manageable?",
        subheading: "",
        text: "",
        cta: "Schedule a Demo",
        media: "",
        notes: "",
      },
    ],
  },
  marketingcreatives: {
    id: "marketingcreatives",
    label: "Marketing Creatives",
    path: "/retailroles/marketingcreatives",
    title: "Marketing Creatives",
    description: "MARKETING CREATIVES",
    sections: [
      {
        order: 1.0,
        section: "Hero",
        heading: "Marketing Creatives",
        subheading: "Know your customers. Launch promotions faster.",
        text: "Turn store traffic into loyal members with clearer customer insights, faster promo execution, and campaigns you can measure—without relying on manual data pulls every time.",
        cta: "Request a Demo",
        media: "/images/retailroles/marketingcreatives.png",
        notes: "",
      },
      {
        order: 2.0,
        section: "Benefits",
        heading: "Built for Retail Marketing That Performs",
        subheading:
          "Solutions to help you understand customers, launch campaigns quickly, and keep improving results.",
        text: "360° customer golden records\nBuild a single view of each customer—purchase history, preferences, and engagement—so targeting and personalization become easy.\n\nKey retail metrics, instantly\nSee and pull the metrics that matter (sales, basket size, frequency, returning customers) without hunting across reports.\n\nAdvanced customer analytics\nUse segmentation, churn signals, RFM scoring, and affinity insights to design smarter campaigns and offers.\n\nLoyalty program management\nRun loyalty programs that reward the behaviors you want—enrollment, repeat visits, higher baskets, and retention.\n\nIn-store promotions made simple\nLaunch and manage in-store promos with less back-and-forth—consistent rules across branches and channels.\n\nEmail campaigns for members\nSend targeted email campaigns to loyalty members for announcements, promos, and re-engagement.\n\nSMS campaigns for members\nReach members quickly with SMS for urgent promos, reminders, and timely nudges.\n\nDual display ads option\nUse store dual displays to run ads and promo creatives at checkout—turning every transaction into a marketing moment.",
        cta: "",
        media: "",
        notes: "",
      },
      {
        order: 3.0,
        section: "CTA",
        heading: "Ready to run faster, smarter retail campaigns?",
        subheading: "",
        text: "",
        cta: "Schedule a Demo",
        media: "",
        notes: "",
      },
    ],
  },
  merchandisers: {
    id: "merchandisers",
    label: "Merchandisers",
    path: "/retailroles/merchandisers",
    title: "Merchandisers",
    description: "MERCHANDISERS",
    sections: [
      {
        order: 1.0,
        section: "Hero",
        heading: "Merchandisers",
        subheading: "Right items. Right price. Right promos. Right inventory.",
        text: "Keep shelves full and assortments on point with tighter replenishment, clearer sales and inventory visibility, and centralized control of products, pricing, and promotions across all stores.",
        cta: "Request a Demo",
        media: "/images/retailroles/merchandisers.png",
        notes: "",
      },
      {
        order: 2.0,
        section: "Benefits",
        heading: "Built for Smarter Assortment and Replenishment",
        subheading:
          "Everything you need to plan, execute, and optimize merchandising across stores—faster and with fewer stock surprises.",
        text: "Robust inventory management & purchasing\nEnsure availability with reliable inventory, purchasing, and replenishment flows—from ordering to receiving to stock updates.\n\nSales reporting at every level\nAnalyze sales per store, per category, per brand, and down to each SKU—so you can act on what’s really moving.\n\nInventory reporting that prevents surprises\nTrack stock on hand, aging, fast/slow movers, and stock-outs to reduce lost sales and overstock.\n\nCentralized product & pricing maintenance\nMaintain product masters and pricing centrally and push updates consistently across all stores—no messy branch-by-branch edits.\n\nAdvanced promotions you can leverage\nRun complex promotions (mix-and-match, bundles, tiers, conditions) without manual work—so execution matches the plan.\n\nCustomer loyalty programs that drive repeat\nCreate and manage loyalty programs that encourage repeat visits and higher baskets, tied directly to real purchase behavior.\n\nMobile inventory management app\nMove faster with a mobile app for receiving, transfers, adjustments, and other inventory movements—less paperwork, fewer delays.\n\nConcessionaire handling for department stores\nSupport concessionaire/vendor setups with clearer accountability, sales tracking, and settlement workflows.\n\nAdvanced analytics for MoM and YTD trends\nTrack month-on-month and year-to-date trends to spot shifts early, plan better, and defend decisions with data.\n\nVendor portal to monetize data\nOffer vendors a portal for insights and performance reporting—creating new value (and potential revenue) from your retail data.",
        cta: "",
        media: "",
        notes: "",
      },
      {
        order: 3.0,
        section: "CTA",
        heading: "Ready to make merchandising more predictable and profitable?",
        subheading: "",
        text: "",
        cta: "Schedule a Demo",
        media: "",
        notes: "",
      },
    ],
  },
  executives: {
    id: "executives",
    label: "Executives",
    path: "/retailroles/executives",
    title: "Executives",
    description: "EXECUTIVES",
    sections: [
      {
        order: 1.0,
        section: "Hero",
        heading: "Executives",
        subheading:
          "Clarity across the business. Faster decisions. Better profit.",
        text: "Get a single, trusted view of sales, margins, inventory health, promos, and customer growth—so you can spot issues early, scale what works, and keep teams accountable across every store.",
        cta: "Request a Demo",
        media: "/images/retailroles/executives.png",
        notes: "",
      },
      {
        order: 2.0,
        section: "Benefits",
        heading: "Built for Visibility, Control, and Growth",
        subheading:
          "Executive-level insights and controls that make performance easier to manage across stores, categories, and regions.",
        text: "Company-wide dashboards that executives actually use\nKey retail metrics that are easy to grasp and retrieve—sales, margin, basket size, transactions, growth, and store performance.\n\nPerformance views by store, region, category, brand, and SKU\nDrill down from enterprise to details without waiting for manual reports.\n\nMonth-on-month and YTD trend analytics\nTrack momentum and detect shifts early—spot weakening categories, improving regions, and promo lift vs. normal.\n\nPromo and pricing governance at scale\nCentralized product and pricing maintenance plus advanced promotion controls—consistent execution across all stores.\n\nInventory health and availability visibility\nSee stock-outs, overstock risk, and inventory movements with clear reporting—protecting sales and working capital.\n\nCustomer growth and loyalty impact\n360° customer records plus loyalty program performance—understand retention, repeat behavior, and what drives frequency.\n\nOperational resilience you can trust\nOffline selling, auto-sync, and recovery from power interruption—so revenue doesn’t stop when outages happen.\n\nAudit-ready reporting and compliance support\nConsolidated reporting (including store Z-readings) plus compliance support for BIR and mall requirements.",
        cta: "",
        media: "",
        notes: "",
      },
      {
        order: 3.0,
        section: "CTA",
        heading: "Want faster decisions with fewer blind spots?",
        subheading: "",
        text: "",
        cta: "Schedule a Demo",
        media: "",
        notes: "",
      },
    ],
  },
  storeoperations: {
    id: "storeOperations",
    label: "Store Operations",
    path: "/retailroles/storeoperations",
    title: "Store Operations",
    description: "STORE OPERATIONS",
    sections: [
      {
        order: 1.0,
        section: "Hero",
        heading: "Store Operations",
        subheading: "Smoother stores. Faster coaching. Cleaner execution.",
        text: "Run better shifts with fewer cashier issues, clearer store performance visibility, and faster promo execution. Keep teams accountable with reports, controls, and audit trails that make daily ops easier.",
        cta: "Request a Demo",
        media: "/images/retailroles/storeoperations.png",
        notes: "",
      },
      {
        order: 2.0,
        section: "Benefits",
        heading: "Built for Daily Execution and Accountability",
        subheading:
          "Tools for store managers, area managers, and regional leaders to keep stores consistent, compliant, and performing.",
        text: "Shift, cashier, and end-of-day reporting\nEoD, shift, and cashier reports that speed up handovers, reconciliation, and accountability.\n\nStore performance at a glance\nSales reports you can review by store, category, brand, and SKU—so coaching is based on facts, not guesses.\n\nStronger controls at the counter\nOverrides for sensitive actions plus alerts (e.g., multiple voids) to reduce leakage and enforce discipline.\n\nOffline continuity during outages\nStores keep selling even when the internet is down, with transactions syncing when back online.\n\nRecover from power interruptions\nRetrieve suspended orders and continue quickly after disruptions—protect lines and prevent lost sales.\n\nExecute promos consistently across stores\nAdvanced promotions that apply automatically at checkout—less confusion, fewer disputes, cleaner execution.\n\nLoyalty enrollment and perks that “just work”\nLoyalty programs applied automatically so frontliners don’t need manual steps—and customers feel the benefits.\n\nCentral Z-reading visibility for ops leaders\nConsolidated Z-readings across stores to support audits, variance checks, and regional monitoring.\n\nFaster inventory movements at store level\nMobile inventory tools to speed up receiving, transfers, and adjustments—less paperwork, fewer stock errors.\n\nSupport that’s easy to escalate\nDedicated support with ticketing so issues are tracked, owned, and resolved with less follow-up from store teams.",
        cta: "",
        media: "",
        notes: "",
      },
      {
        order: 3.0,
        section: "CTA",
        heading: "Ready to run smoother stores week after week?",
        subheading: "",
        text: "",
        cta: "Schedule a Demo",
        media: "",
        notes: "",
      },
    ],
  },
};
